(ns gnostica.app.registrations.subscriptions.move
  (:require [gnostica.app.ids :as ids]
            [gnostica.app.registrations.subscriptions.helpers :as helpers]
            [gnostica.app-state :as app-state]
            [re-frame.core :as rf]))

(helpers/register-db-subscriptions!
 [[ids/move-source-options app-state/move-source-options]
  [ids/move-prompt app-state/move-prompt]
  [ids/move-ready? app-state/move-ready?]
  [ids/move-control-groups app-state/move-control-groups]
  [ids/move-action-ribbon app-state/move-action-ribbon]
  [ids/move-piece-options app-state/move-piece-options]
  [ids/move-hand-card-options app-state/move-hand-card-options]
  [ids/move-discard-card-options app-state/move-discard-card-options]
  [ids/move-source-board-options app-state/move-source-board-options]
  [ids/move-target-board-options app-state/move-target-board-options]
  [ids/move-target-wasteland-options app-state/move-target-wasteland-options]
  [ids/move-one-point-card-options app-state/move-one-point-card-options]
  [ids/move-territory-card-source-options app-state/move-territory-card-source-options]
  [ids/move-power-options app-state/move-power-options]
  [ids/move-power app-state/move-power]
  [ids/move-world-copy-options app-state/move-world-copy-options]
  [ids/move-world-copied-power-options app-state/move-world-copied-power-options]
  [ids/move-world-copied-power app-state/move-world-copied-power]
  [ids/move-rod-mode-options app-state/move-rod-mode-options]
  [ids/move-disc-action-count-options app-state/move-disc-action-count-options]
  [ids/move-major-action-count-options app-state/move-major-action-count-options]
  [ids/move-major-action-count app-state/move-major-action-count]
  [ids/move-sword-action-count-options app-state/move-sword-action-count-options]
  [ids/move-devil-action-count-options app-state/move-devil-action-count-options]
  [ids/move-sun-disc-mode-options app-state/move-sun-disc-mode-options]
  [ids/move-fool-reveal-count-options app-state/move-fool-reveal-count-options]
  [ids/move-fool-reveal-state app-state/move-fool-reveal-state]
  [ids/move-fool-play-power-options app-state/move-fool-play-power-options]
  [ids/move-fool-play-power app-state/move-fool-play-power]
  [ids/move-high-priestess-redraw-count-options app-state/move-high-priestess-redraw-count-options]
  [ids/move-high-priestess-redraw-options app-state/move-high-priestess-redraw-options]
  [ids/move-judgement-card-options app-state/move-judgement-card-options]
  [ids/move-judgement-card-maximum app-state/move-judgement-card-maximum]
  [ids/move-disc-minion-orientation-required? app-state/move-disc-minion-orientation-required?]
  [ids/move-disc-target-kind-options app-state/move-disc-target-kind-options]
  [ids/move-sword-target-kind-options app-state/move-sword-target-kind-options]
  [ids/move-legal-targets app-state/move-legal-targets]
  [ids/move-preview app-state/move-preview]
  [ids/move-target-piece-options app-state/move-target-piece-options]
  [ids/move-distance-options app-state/move-distance-options]
  [ids/move-damage-options app-state/move-damage-options]
  [ids/move-disc-orientation-available? app-state/move-disc-orientation-available?]
  [ids/move-sun-disc-orientation-available? app-state/move-sun-disc-orientation-available?]
  [ids/move-sword-orientation-available? app-state/move-sword-orientation-available?]
  [ids/move-replacement-card-options app-state/move-replacement-card-options]
  [ids/move-orientation-options app-state/move-orientation-options]
  [ids/draw-count-options app-state/draw-count-options]])

(rf/reg-sub
 ids/move-rod-orientation-required?
 (fn [db _]
   (or (app-state/move-rod-orientation-required? db)
       (app-state/move-hermit-orientation-required? db))))
