(ns gnostica.smoke.page-stats.readiness
  (:require [clojure.string :as str]
            [gnostica.fixtures :as fixtures]
            [gnostica.icon-layout :as icon-layout]
            [gnostica.icons :as icons]
            [gnostica.keyboard-shortcuts :as shortcuts]
            [gnostica.smoke.page-stats.pixels :as pixels]))

(defn antialias-ready? [stats]
  (and (true? (get stats "antialiasRequested"))
       (or (false? (get stats "antialiasSupported"))
           (true? (get stats "antialiasEnabled")))))
(defn roughly= [expected actual tolerance]
  (<= (Math/abs (- (double expected) (double actual))) tolerance))
(defn dom-icon-layout-ready? [metrics]
  (let [width-ratio (double (or (get metrics "widthRatio") 0))
        gap (double (or (get metrics "gap") -1))
        icon-width (double (or (get metrics "iconWidth") 0))]
    (and (map? metrics)
         (= icon-layout/card-icon-scale
            (long (or (get metrics "scale") -1)))
         (roughly= (/ icon-layout/dom-card-icon-width-percent 100.0)
                   width-ratio
                   0.03)
         (roughly= icon-layout/dom-card-icon-gap-px gap 1.0)
         (pos? icon-width))))
(defn mobile-header-context-ready? [stats]
  (let [text (str (or (get stats "mobileGameContextText") "")
                  " "
                  (or (get stats "mobileGameContextAriaLabel") ""))]
    (and (true? (get stats "mobileGameContext"))
         (true? (get stats "mobileGameContextVisible"))
         (str/includes? text "Current player")
         (str/includes? text "Rose")
         (str/includes? text "score")
         (str/includes? text "/9"))))
(defn- desktop-header-context-ready? [stats]
  (and (true? (get stats "appStatusVisible"))
       (true? (get stats "appScoresVisible"))
       (str/includes? (or (get stats "appStatusText") "") "Current player")
       (str/includes? (or (get stats "appStatusText") "") "Rose")
       (str/includes? (or (get stats "appScoresText") "") "target")))
(defn- header-context-ready? [stats]
  (if (<= (long (or (get stats "viewportWidth") 0)) 520)
    (mobile-header-context-ready? stats)
    (desktop-header-context-ready? stats)))
(defn short-mobile-gameplay-reachable? [stats]
  (let [scroll-height (long (or (get stats "scrollHeight") 0))
        client-height (long (or (get stats "clientHeight") 0))
        requested-scroll-y (long (or (get stats "requestedScrollY") 0))
        scroll-y-after (long (or (get stats "scrollYAfter") 0))
        blocked-overflows #{"hidden" "clip"}]
    (and (not (contains? blocked-overflows (get stats "bodyOverflowY")))
         (pos? scroll-height)
         (pos? client-height)
         (> scroll-height client-height)
         (pos? requested-scroll-y)
         (<= (- requested-scroll-y 2) scroll-y-after)
         (true? (get stats "moveToggle"))
         (true? (get stats "cardsToggle"))
         (true? (get stats "topHeaderVisible"))
         (true? (get stats "topBoardVisible"))
         (true? (get stats "cardsPanelReachable"))
         (true? (get stats "movePanelReachable"))
         (true? (get stats "moveSourceReachable"))
         (true? (get stats "sideStackVisible"))
         (not (contains? blocked-overflows (get stats "sideStackOverflowY"))))))
(defn three-icon-layout-ready? [stats]
  (and (= icon-layout/card-icon-scale
          (long (or (get stats "cardIconScale") -1)))
       (= icon-layout/texture-card-icon-size
          (long (or (get stats "cardIconSize") -1)))
       (= (count icons/icon-ids)
          (long (or (get stats "cardTextureSupportedIconCount") -1)))
       (= icon-layout/max-card-icon-count
          (long (or (get stats "cardTextureMaxIconCount") -1)))
       (true? (get stats "cardTextureIconStackFits"))))
(defn happy-ready? [stats]
  (let [visible-piece-count (long (or (get stats "visiblePieceCount") -1))
        piece-edge-outline-count (long (or (get stats "pieceEdgeOutlineCount") -1))
        viewport-width (long (or (get stats "viewportWidth") 0))
        viewport-height (long (or (get stats "viewportAvailableHeight") 0))
        shell-width (long (or (get stats "shellClientWidth") 0))
        shell-height (long (or (get stats "shellClientHeight") 0))
        board-width (long (or (get stats "boardClientWidth") 0))
        board-height (long (or (get stats "boardClientHeight") 0))
        canvas-width (long (or (get stats "canvasClientWidth") 0))
        canvas-height (long (or (get stats "canvasClientHeight") 0))]
    (and (= "128" (get stats "threeRevision"))
         (= "always" (get stats "cardIconMode"))
         (true? (get stats "orbitControls"))
         (true? (get stats "board"))
         (str/includes? (or (get stats "boardAriaLabel") "")
                        (str "with " (get stats "boardCardCount")
                             " face-up tarot territory cards"))
         (<= (- viewport-width 2) shell-width)
         (<= (- viewport-height 2) shell-height)
         (<= (- shell-width 2) board-width)
         (<= (- shell-height 2) board-height)
         (<= (- board-width 2) canvas-width)
         (<= (- board-height 2) canvas-height)
         (= "always" (get stats "boardCardIconMode"))
         (= 2 (long (or (get stats "majorIconCardCount") -1)))
         (= 5 (long (or (get stats "majorIconCount") -1)))
         (three-icon-layout-ready? stats)
         (= 12 (get stats "wastelandCount"))
         (= (count fixtures/smoke-board-pieces) visible-piece-count)
         (= visible-piece-count piece-edge-outline-count)
         (= pixels/expected-table-surface-color (get stats "tableSurfaceColor"))
         (= pixels/expected-table-clear-color (get stats "tableClearColor"))
         (false? (get stats "fallback"))
         (true? (get stats "canvas"))
         (pos? canvas-width)
         (pos? canvas-height)
         (antialias-ready? stats)
         (roughly= 3.2 (double (or (get stats "minZoomDistance") -1)) 0.001)
         (roughly= 10.0 (double (or (get stats "maxZoomDistance") -1)) 0.001)
         (<= 3.2 (double (or (get stats "cameraDistance") -1)) 10.0)
         (number? (get stats "cameraTargetX"))
         (number? (get stats "cameraTargetY"))
         (true? (get stats "reset"))
         (header-context-ready? stats)
         (true? (get stats "cardZones"))
         (true? (get stats "cardZonesVisible"))
         (= 6 (long (or (get stats "handCardCount") -1)))
         (= 1 (long (or (get stats "handMajorIconStackCount") -1)))
         (= 1 (long (or (get stats "handMajorIconCount") -1)))
         (dom-icon-layout-ready? (get stats "handIconMetrics"))
         (pos? (long (or (get stats "drawCount") 0)))
         (zero? (long (or (get stats "discardCount") -1)))
         (empty? (get stats "status"))
         (>= (long (or (get stats "imageResourceCount") 0)) 9))))
(defn camera-distance-changed? [initial-stats stats]
  (let [initial-distance (double (or (get initial-stats "cameraDistance") -1))
        current-distance (double (or (get stats "cameraDistance") -1))]
    (and (pos? initial-distance)
         (pos? current-distance)
         (not (roughly= initial-distance current-distance 0.05)))))
(defn camera-distance-preserved? [expected-stats stats]
  (let [expected-distance (double (or (get expected-stats "cameraDistance") -1))
        current-distance (double (or (get stats "cameraDistance") -1))]
    (and (pos? expected-distance)
         (pos? current-distance)
         (roughly= expected-distance current-distance 0.02))))
(defn camera-target-preserved? [expected-stats stats]
  (let [expected-x (double (or (get expected-stats "cameraTargetX") -999))
        expected-y (double (or (get expected-stats "cameraTargetY") -999))
        current-x (double (or (get stats "cameraTargetX") -999))
        current-y (double (or (get stats "cameraTargetY") -999))]
    (and (not= -999.0 expected-x)
         (not= -999.0 expected-y)
         (not= -999.0 current-x)
         (not= -999.0 current-y)
         (roughly= expected-x current-x 0.02)
         (roughly= expected-y current-y 0.02))))
(defn camera-target-x-changed? [initial-stats stats]
  (let [initial-x (double (or (get initial-stats "cameraTargetX") -999))
        current-x (double (or (get stats "cameraTargetX") -999))]
    (not (roughly= initial-x current-x 0.05))))
(defn camera-target-y-changed? [initial-stats stats]
  (let [initial-y (double (or (get initial-stats "cameraTargetY") -999))
        current-y (double (or (get stats "cameraTargetY") -999))]
    (not (roughly= initial-y current-y 0.05))))
(defn fallback-ready? [stats]
  (and (nil? (get stats "threeRevision"))
       (= "always" (get stats "cardIconMode"))
       (false? (get stats "orbitControls"))
       (true? (get stats "fallback"))
       (= "always" (get stats "boardCardIconMode"))
       (false? (get stats "canvas"))
       (= pixels/expected-table-surface-color (get stats "tableSurfaceColor"))
       (= pixels/expected-table-clear-color (get stats "tableClearColor"))
       (= 9 (get stats "cssCards"))
       (= 2 (long (or (get stats "cssMajorIconStackCount") -1)))
       (= 5 (long (or (get stats "cssMajorIconCount") -1)))
       (dom-icon-layout-ready? (get stats "cssBoardIconMetrics"))
       (= 12 (get stats "cssWastelands"))
       (= 1 (long (or (get stats "cssWastelandPieceMarkers") -1)))
       (true? (get stats "cardZones"))
       (true? (get stats "cardZonesVisible"))
       (= 6 (long (or (get stats "handCardCount") -1)))
       (= 1 (long (or (get stats "handMajorIconStackCount") -1)))
       (= 1 (long (or (get stats "handMajorIconCount") -1)))
       (dom-icon-layout-ready? (get stats "handIconMetrics"))
       (pos? (long (or (get stats "drawCount") 0)))
       (zero? (long (or (get stats "discardCount") -1)))
       (str/includes? (or (get stats "statusText") "") "Three.js is unavailable")))
(defn mismatch-ready? [stats]
  (and (= "999" (get stats "threeRevision"))
       (= "always" (get stats "cardIconMode"))
       (true? (get stats "orbitControls"))
       (true? (get stats "fallback"))
       (= "always" (get stats "boardCardIconMode"))
       (false? (get stats "canvas"))
       (= pixels/expected-table-surface-color (get stats "tableSurfaceColor"))
       (= pixels/expected-table-clear-color (get stats "tableClearColor"))
       (= 9 (get stats "cssCards"))
       (= 2 (long (or (get stats "cssMajorIconStackCount") -1)))
       (= 5 (long (or (get stats "cssMajorIconCount") -1)))
       (dom-icon-layout-ready? (get stats "cssBoardIconMetrics"))
       (= 12 (get stats "cssWastelands"))
       (true? (get stats "cardZones"))
       (true? (get stats "cardZonesVisible"))
       (= 6 (long (or (get stats "handCardCount") -1)))
       (= 1 (long (or (get stats "handMajorIconStackCount") -1)))
       (= 1 (long (or (get stats "handMajorIconCount") -1)))
       (dom-icon-layout-ready? (get stats "handIconMetrics"))
       (pos? (long (or (get stats "drawCount") 0)))
       (zero? (long (or (get stats "discardCount") -1)))
       (str/includes? (or (get stats "statusText") "") "revision 999 is incompatible")))
(defn popup-mode-ready? [stats]
  (let [hand (get stats "hand")
        board-two (get stats "boardTwo")
        board-three (get stats "boardThree")
        fallback? (true? (get stats "fallback"))]
    (and (= "popup" (get stats "appMode"))
         (= "popup" (get stats "boardMode"))
         (= "false" (get stats "togglePressed"))
         (zero? (long (or (get stats "handStackCount") -1)))
         (zero? (long (or (get stats "textureErrorCount") -1)))
         (empty? (get stats "textureStatus"))
         (true? (get hand "visible"))
         (= 1 (long (or (get hand "iconCount") -1)))
         (str/includes? (or (get hand "text") "") "Sword, rod, cup, or disc")
         (true? (get board-two "visible"))
         (= 2 (long (or (get board-two "iconCount") -1)))
         (str/includes? (or (get board-two "text") "") "Rod")
         (or (not fallback?)
             (and (true? (get board-three "visible"))
                  (= 3 (long (or (get board-three "iconCount") -1)))
                  (str/includes? (or (get board-three "text") "")
                                 "Orient a target piece"))))))
(defn hotkey-help-open-ready? [stats]
  (let [labels (set (get stats "keyLabels"))
        expected-labels (set (shortcuts/hotkey-command-labels))
        board-command (:command (shortcuts/command-by-id :pan-board-view))]
    (and (true? (get stats "overlayVisible"))
         (true? (get stats "dialogVisible"))
         (= "dialog" (get stats "role"))
         (= "true" (get stats "ariaModal"))
         (true? (get stats "backgroundInert"))
         (= "true" (get stats "backgroundAriaHidden"))
         (true? (get stats "activeInDialog"))
         (true? (get stats "closeFocused"))
         (str/includes? (get stats "title") "Keyboard Commands")
         (= (count shortcuts/hotkey-commands)
            (long (or (get stats "commandCount") -1)))
         (every? #(contains? labels %) expected-labels)
         (str/includes? (or (get stats "text") "") board-command))))
(defn icon-help-open-ready? [stats]
  (and (true? (get stats "overlayVisible"))
       (true? (get stats "dialogVisible"))
       (= "dialog" (get stats "role"))
       (= "true" (get stats "ariaModal"))
       (true? (get stats "backgroundInert"))
       (= "true" (get stats "backgroundAriaHidden"))
       (true? (get stats "activeInDialog"))
       (true? (get stats "closeFocused"))
       (str/includes? (get stats "title") "Special Move Icons")
       (= (count icons/icon-ids) (long (or (get stats "itemCount") -1)))
       (= (count icons/icon-ids) (long (or (get stats "iconCount") -1)))
       (str/includes? (or (get stats "text") "") "Create a small piece")
       (str/includes? (or (get stats "text") "") "Any major arcana power")))
(defn icon-help-closed-ready? [stats]
  (and (false? (get stats "overlayVisible"))
       (false? (get stats "dialogVisible"))
       (false? (get stats "backgroundInert"))
       (nil? (get stats "backgroundAriaHidden"))
       (zero? (long (or (get stats "itemCount") -1)))))
(defn hotkey-help-closed-ready? [stats]
  (and (false? (get stats "overlayVisible"))
       (false? (get stats "dialogVisible"))
       (false? (get stats "backgroundInert"))
       (nil? (get stats "backgroundAriaHidden"))
       (zero? (long (or (get stats "commandCount") -1)))))
(defn hotkey-help-closed-board-restored? [stats]
  (and (hotkey-help-closed-ready? stats)
       (true? (get stats "boardFocused"))))
(defn icon-help-closed-board-restored? [stats]
  (and (icon-help-closed-ready? stats)
       (true? (get stats "boardFocused"))))
(defn icon-help-closed-toggle-restored? [stats]
  (and (icon-help-closed-ready? stats)
       (true? (get stats "iconToggleFocused"))))
(defn center-card-selected? [selection]
  (str/includes? (or (get selection "panelText") "") "Row 2, Column 2"))
(defn move-panel-hand-card-step-ready? [stats]
  (and (true? (get stats "panelOpen"))
       (true? (get stats "panelActive"))
       (= "Play hand card" (get stats "selectedSourceLabel"))
       (true? (get stats "handCardStep"))
       (= 6 (long (or (get stats "handCardChoiceCount") -1)))))
(defn pending-tray-needs-choice-ready? [stats]
  (and (true? (get stats "active"))
       (= "Needs choice" (get stats "status"))
       (seq (get stats "summary"))
       (true? (get stats "confirmVisible"))
       (false? (get stats "canConfirm"))
       (true? (get stats "cancelVisible"))
       (true? (get stats "detailedVisible"))))
(defn pending-tray-ready? [stats]
  (and (true? (get stats "active"))
       (= "Ready" (get stats "status"))
       (seq (get stats "summary"))
       (true? (get stats "confirmVisible"))
       (true? (get stats "canConfirm"))
       (true? (get stats "cancelVisible"))))
(defn pending-tray-detailed-open-ready? [stats]
  (and (pending-tray-needs-choice-ready? stats)
       (= "true" (get stats "detailedPressed"))
       (true? (get stats "panelOpen"))
       (true? (get stats "panelActive"))))
(defn pending-tray-ready-detailed-east? [stats]
  (and (pending-tray-ready? stats)
       (= "true" (get stats "detailedPressed"))
       (true? (get stats "panelOpen"))
       (true? (get stats "panelActive"))
       (= "East" (get stats "selectedOrientation"))))
(defn keyboard-placement-target-started? [stats]
  (and (pending-tray-needs-choice-ready? stats)
       (= "territory" (get stats "previewTargetKind"))
       (= 4 (long (or (get stats "previewTargetBoardIndex") -1)))
       (nil? (get stats "previewPlacementOrientation"))))
(defn keyboard-placement-target-moved? [stats]
  (and (pending-tray-needs-choice-ready? stats)
       (= "territory" (get stats "previewTargetKind"))
       (= 5 (long (or (get stats "previewTargetBoardIndex") -1)))
       (nil? (get stats "previewPlacementOrientation"))))
(defn keyboard-placement-ready-east? [stats]
  (and (pending-tray-ready? stats)
       (= "territory" (get stats "previewTargetKind"))
       (= 5 (long (or (get stats "previewTargetBoardIndex") -1)))
       (= "east" (get stats "previewPlacementOrientation"))))
(defn- first-piece-source-icon-ready? [stats]
  (and (= "small-pyramid" (get stats "firstPieceSourceIconShape"))
       (str/includes? (or (get stats "firstPieceSourceIconClipPath") "")
                      "polygon")
       (= "rgb(232, 93, 117)" (get stats "firstPieceSourceIconColor"))
       (true? (get stats "firstPieceSourceIconPipVisible"))))
(defn direct-drop-fallback-ready? [stats]
  (and (true? (get stats "fallback"))
       (false? (get stats "canvas"))
       (= 9 (long (or (get stats "cssCards") -1)))
       (= 12 (long (or (get stats "cssWastelands") -1)))
       (zero? (long (or (get stats "pieceCount") -1)))
       (true? (get stats "movePanelOpen"))
       (false? (get stats "movePanelActive"))
       (true? (get stats "firstPieceSourceVisible"))
       (false? (get stats "firstPieceSourceDisabled"))
       (first-piece-source-icon-ready? stats)
       (true? (get stats "pointerDragEnabled"))
       (= pixels/expected-table-surface-color (get stats "tableSurfaceColor"))
       (= pixels/expected-table-clear-color (get stats "tableClearColor"))
       (str/includes? (or (get stats "statusText") "") "Three.js is unavailable")))
(defn direct-drop-three-ready? [stats]
  (and (false? (get stats "fallback"))
       (true? (get stats "canvas"))
       (zero? (long (or (get stats "pieceCount") -1)))
       (true? (get stats "movePanelOpen"))
       (false? (get stats "movePanelActive"))
       (true? (get stats "firstPieceSourceVisible"))
       (false? (get stats "firstPieceSourceDisabled"))
       (first-piece-source-icon-ready? stats)
       (true? (get stats "pointerDragEnabled"))))
(defn direct-drop-confirmed? [stats]
  (and (true? (get stats "fallback"))
       (false? (get stats "canvas"))
       (= 1 (long (or (get stats "pieceCount") -1)))
       (= 1 (long (or (get stats "eastPieceCount") -1)))
       (= 1 (long (or (get stats "smallPieceCount") -1)))
       (= 1 (long (or (get stats "rosePieceCount") -1)))
       (false? (get stats "pendingActive"))
       (true? (get stats "firstPieceSourceDisabled"))))
(defn wasteland-click-confirmed? [stats]
  (and (direct-drop-confirmed? stats)
       (= 1 (long (or (get stats "wastelandPieceCount") -1)))))
(defn direct-drop-three-confirmed? [stats]
  (and (false? (get stats "fallback"))
       (true? (get stats "canvas"))
       (= 1 (long (or (get stats "pieceCount") -1)))
       (false? (get stats "pendingActive"))
       (false? (get stats "dragGhostVisible"))
       (false? (get stats "sourceDragGhostVisible"))
       (true? (get stats "firstPieceSourceDisabled"))))
(defn touch-input-ready? [stats]
  (and (map? stats)
       (pos? (long (or (get stats "touchStartCount") 0)))
       (pos? (long (or (get stats "touchEndCount") 0)))))
(defn touch-drag-input-ready? [stats]
  (and (touch-input-ready? stats)
       (pos? (long (or (get stats "touchMoveCount") 0)))))
(defn pending-tray-closed? [stats]
  (false? (get stats "active")))
